### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1


### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1


### Verbo POST – adicionar
POST  http://localhost:8000/cliente/ HTTP/1.1
Content-Type: application/json

{
    "nome" : "Eduarda Claumann",
    "cpf" : "01177480999",
    "telefone" : "49999378801",
    "email" : "eduarda@gmail.com"
}


### Verbo PUT – atualiza
PUT  http://localhost:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Eduarda Claumann",
    "cpf" : "01177480999",
    "telefone" : "49999378801",
    "email" : "eduarda@gmail.com"
}

### Verbo DELETE – excluir
DELETE  http://localhost:8000/cliente/2 HTTP/1.1
